name: Test multi-arch build

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  readme-release:
    runs-on: ubuntu-latest
    env:
      VERSIONTAG_THIS: ""
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            baschny/php-extension-installer:latest
          platforms: linux/amd64,linux/arm64
